services:
  dev_app:
    extends:
      file: ./docker-compose.base.yml
      service: app
    container_name: dev_app
    profiles:
      - dev
    depends_on:
      - mailhog
      - redis
      - dev_postgres
    command: >
      sh -c '
        npm ci &&
        npm run start;
      '
    networks:
      - dev-bridge

  test_app:
    extends:
      file: ./docker-compose.base.yml
      service: app
    container_name: test_app
    profiles:
      - test
    depends_on:
      - mailhog
      - redis
      - test_postgres
    command: >
      sh -c '
        npm ci;
        npm run test;
      '
    networks:
      - test-bridge

  dev_postgres:
    extends:
      file: ./docker-compose.base.yml
      service: postgres
    volumes:
      - ./docker/local/postgres/pgdata:/var/lib/postgresql/data
    profiles:
      - dev
      - localDev
    networks:
      - dev-bridge

  test_postgres:
    extends:
      file: ./docker-compose.base.yml
      service: postgres
    profiles:
      - test
      - localTest
    networks:
      - test-bridge

  mailhog:
    extends:
      file: ./docker-compose.base.yml
      service: mailhog
    profiles:
      - dev
      - test
      - localDev
      - localTest
    networks:
      - test-bridge
      - dev-bridge

  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis
    profiles:
      - dev
      - test
      - localDev
      - localTest
    networks:
      - test-bridge
      - dev-bridge


networks:
  test-bridge:
    driver: bridge
  dev-bridge:
    driver: bridge