services:
  app:
    image: node:22.8.0
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - COOKIE_SECRET_KEY=${COOKIE_SECRET_KEY}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_HOST=${EMAIL_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTRY_DNS=${SENTRY_DNS}

  postgres:
    image: postgres:17.2
    shm_size: 1gb
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGPORT=${POSTGRES_PORT}
    restart: always

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${EMAIL_SMTP_PORT}:${EMAIL_SMTP_PORT}  # SMTP port for sending emails
      - ${EMAIL_HTTP_PORT}:${EMAIL_HTTP_PORT}  # HTTP interface for viewing emails
    environment:
      - MH_STORAGE=memory
      - MH_SMTP_AUTH=true  # Enable SMTP authentication
      - MH_SMTP_USER=${EMAIL_USER}  # Set the SMTP username
      - MH_SMTP_PASSWORD=${EMAIL_PASSWORD}

  redis:
    image: redis:7.4
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --port ${REDIS_PORT}
      --maxmemory 256mb
    restart: always