services:
  app:
    image: node:22.9.0
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install && npm run debug"