name: CI/CD Pipeline

on:
  push:  # Runs on push to any branch
    branches:
      - '**'
  pull_request:  # Runs on all PRs before merging
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      # Clone repository into the GitHub Actions runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Write the secret to .env.test
      - name: Write env variables to file
        run: |
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env.test
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env.test
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env.test

      # Print the contents of .env.test for debugging
      - name: Print .env.test
        run: cat .env.test

      # Buildx is an advanced Docker builder that supports multi-platform builds and caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Tests
        run: |
          docker compose --env-file .env.test --profile test up

      - name: Wait for Tests to Finish
        run: |
          docker wait app

      - name: Stop and Clean Up
        run: docker-compose down